#!/bin/sh
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3
 
NAME=$(git branch | grep '*' | sed 's/* //' | cut -d/ -f2 | cut -d- -f1,2)
DESCRIPTION=$(git config branch."$NAME".description)
 
if cat $1 | head -1 | grep -q "$NAME";
then
   echo "$(cat $1)" > "$1"
else
   echo "$NAME:  $(cat $1)" > "$1"
fi
 
if [ -n "$DESCRIPTION" ]
then
   echo $DESCRIPTION >> "$1"
fi
